### PR TITLE
Optimize lodash import to reduce bundle size

### PR DESCRIPTION
**Pull request by t47io**
Import lodash functions by pick, not the full lib. See analogously this: https://www.npmjs.com/package/babel-plugin-lodash

### CODE REVIEW

**Comment by gilbox** [comment]
thanks for your contribution. do you have an npm user name?

**Comment by t47io** [comment]
thanks! not yet for npm account, will do soon :)

**Comment by t47io** [comment]
@gilbox Could you make a release? so that `npm install` will get the changes.

**Comment by t47io** [comment]
did so, see if need to revise: https://github.com/gilbox/react-spark-scroll/releases/tag/v2.0.3

not sure how to push to `npm` though.

**Comment by gilbox** [comment]
@t47io please create an account here https://www.npmjs.com/
... and tell me your user name

**Comment by t47io** [comment]
its `t47io`, thanks

**Comment by gilbox** [comment]
@t47io you should now have permission to publish. Make sure that you do **not** run `npm publish`. See [instructions here](https://github.com/gilbox/react-spark-scroll#publishing-to-npm)

**Pull request merged**
